name: CI

on: push

jobs:
  test:
    uses: jill64/.github/.github/workflows/run-vitest.yml@main
    with:
      pre-test: pnpm build
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@2eee8a33ad22ebe0cdf9b31ca0db0ac1ab3101d6 # v2.2.5
    with:
      hosting-provider: cloudflare
