name: CI

on: push

jobs:
  test:
    uses: jill64/.github/.github/workflows/run-vitest.yml@main
    with:
      pre-test: pnpm build
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@79be820c194e134cd595ded9bd0258f2297175f3 # v2.4.0
    with:
      hosting-provider: cloudflare
